import { Inter } from "next/font/google";
import style from "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
import Header from "@/componentes/navbar/navbar";
import Footer from "@/componentes/footer/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header></Header>
        {children}
        <Footer></Footer>
        </body>
        
    </html>
  );
}
